#!/bin/sh

#launch led_server and change gpio21 direction
case "$1" in
  start)
    echo "Start of led_server"
    echo 21 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio21/direction
    export PWM_CHIP=pwmchip0
    export PWM=4
    echo $PWM > /sys/class/pwm/$PWM_CHIP/export
    echo 1 > /sys/class/pwm/$PWM_CHIP/pwm$PWM/enable
    echo 100000 > /sys/class/pwm/$PWM_CHIP/pwm$PWM/period
    /root/led_server &
    ;;
  stop)
    echo "Stopping script blah"
    kill -INT `pidof led_server`
    ;;
  *)
    echo "Usage: /etc/init.d/S99app {start|stop}"
    exit 1
    ;;
esac


exit 0
