pdf:
	a2x -v CompteRendu -f pdf --dblatex-opts "-P latex.output.revhistory=0" \
		--dblatex-opts="--param=latex.encoding=utf8"

pdf_fop:
	a2x -v CompteRendu -f pdf --fop

clean:
	rm -f CompteRendu.pdf CompteRendu.xml
